id: P005627
initial_creation_type: ocr
source_metadata:
  id: bdr:W30391
  title: སྐྱ་མོ་ལམ།
  author: ''
  volumes:
    9c557146da004e9c83cded4f7b58568e:
      image_group_id: I1KG16016
      title: ''
      volume_number: 1
      total_pages: 294
