id: P005627
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W30391
  title: སྐྱ་མོ་ལམ།
  author: ''
  volumes:
    9c557146da004e9c83cded4f7b58568e:
      image_group_id: I1KG16016
      title: ''
      volume_number: 1
      total_pages: 294
      base_file: v001.txt
